service: graphidot-serverless-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  versionFunctions: false

  iam:
    role:
      statements:
      
      - Effect: Allow
        Action:
          - 'dynamodb:BatchGetItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:Query'
          - 'dynamodb:Scan'
          - 'dynamodb:BatchWriteItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
        Resource: 'arn:aws:dynamodb:ap-south-1:796111410382:table/graphidot_objects_dev'

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:

  feedback:
    handler: handler.feedback_handler
    events:
      - http:
          path: feedback
          method: post
          cors: true
