service: graphidot-serverless-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  versionFunctions: false
  environment:
    STAGE: ${opt:stage, 'dev'}

  iam:
    role:
      statements:
      
      - Effect: Allow
        Action:
          - 'dynamodb:BatchGetItem'
          - 'dynamodb:GetItem'
          - 'dynamodb:Query'
          - 'dynamodb:Scan'
          - 'dynamodb:BatchWriteItem'
          - 'dynamodb:PutItem'
          - 'dynamodb:UpdateItem'
        Resource: ${file(./config.${opt:stage, 'dev'}.json):GRAPHIDOT_OBJECTS_TABLE_ARN}

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:

  feedback:
    handler: handler.feedback_handler
    events:
      - http:
          path: WebsiteFeedback/Post
          method: post
          cors: true
