service: graphidot-serverless-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1
  versionFunctions: false

plugins:
  - serverless-offline
  - serverless-python-requirements

functions:

  feedback:
    handler: handler.feedback_handler
    events:
      - http:
          path: feedback
          method: post
          cors: true
