name: Deploy PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install node modules
      run: npm install

    - name: install serverless
      run: npm install -g serverless

    - name: check serverless version
      run: serverless --version

    - name: aws cli upgrade
      run: pip3 install awscli --upgrade --user

    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: check pip version
      run: pip3 --version

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: check python version
      run: python3 --version
      
    - name: install python requirements
      run: pip3 install -r requirements.txt

    - name: serverless deploy
      run: sls deploy --stage prod

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} 