name: Deploy DEV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install node modules
      run: npm install

    - name: install serverless
      run: npm install -g serverless

    - name: aws cli upgrade
      run: pip3 install awscli --upgrade --user

    - name: upgrade pip
      run: python -m pip install --upgrade pip

    - name: install python
      run: sudo apt update | sudo apt install software-properties-common | sudo add-apt-repository ppa:deadsnakes/ppa | sudo apt install python3.9

    - name: install python requirements
      run: pip3 install -r requirements.txt

    - name: serverless deploy
      run: sls deploy --stage dev
      # uses: serverless/github-action@v3.2
      # with:
      #   args: deploy
      env:
        # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} # Use your bucket region here